import { MigrationInterface, QueryRunner } from 'typeorm';

export class SetRutaClientes1768515351160 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            UPDATE client
            SET ruta = 'A'
            WHERE nombre IN (
            'Alejandra Mc Intonsh',
            'Andrea Cristi',
            'Magdalena Silva',
            'Felipe Hurtado',
            'Teresita Silva',
            'Nayam Salma',
            'Francisco Suarez',
            'Maria Luisa',
            'Paula Ojeda',
            'Carolina Ruiz',
            'Catalina Lyon',
            'Felipe Mc Laughlin',
            'Juan P.Matte',
            'M. Jose Errazuriz',
            'Fernando Manchant',
            'Anita Orellana',
            'Santiago Long',
            'Cecilia Mena',
            'Mercedes Rodriguez',
            'Paulina Orellana',
            'Angela Barros',
            'Ignacia Feller',
            'Magdalena Varela',
            'Jaime Eyzaguirre',
            'Matias Alessandri',
            'Maria A.Rios',
            'Janine Cooper',
            'Andrea Fernandez',
            'Francisca Arteaga',
            'Adriana Varela',
            'Enrique Brinkman',
            'Catalina Lanas',
            'Martin Larrain',
            'Juan J. Altamirano',
            'Mauricio Silva',
            'Gonzalo Badilla',
            'Patricia Hurtado',
            'Daniela Zecchetto',
            'Alejandro Abarca',
            'Luz Maria Guzman',
            'Cloudine Lopez',
            'Carolina Fortin',
            'Andrea Mery',
            'Ramiro Cadena',
            'Patricio Rifo',
            'Heidi del Rio',
            'Andres Diaz',
            'Pablo Diaz',
            'Beatriz Squella',
            'Dominique Henriquez',
            'Franco Ferrini',
            'Angelica Skalweit',
            'Alejandra Cornejo',
            'Loreto Vargas',
            'Domingo Arteaga',
            'Juan Davila',
            'Paulina Alvarez',
            'Felicita Otero',
            'Cecilia Olivares',
            'Francisco Jaramillo',
            'Angelica Capurro',
            'Paola Dapelo',
            'Veronica Jara',
            'Vanessa Ramos',
            'Rafael Carrasco',
            'Jose Antonio Varas',
            'Irma de la Maza',
            'Santiago Paulovic',
            'Marta Caro',
            'Stefano Di Biase',
            'Javier Genot',
            'Ed. Los Prados de Vitacura',
            'Denis Costa',
            'Marco Berchelino',
            'Vivian Farias',
            'Cristobal Hereimans',
            'Lain Diaz',
            'Jorge Misleh',
            'Cristian Rigeling',
            'Maria Angelica Lanas',
            'Rodrigo Araya',
            'Jose Miguel Castillo'
            );
    `);

    await queryRunner.query(`
            UPDATE client
            SET ruta = 'B'
            WHERE nombre IN (
            'Cond. Las Clarisas',
            'German Fernandino',
            'Javier Julian Fuentes',
            'Com Duble Almeyda',
            'Carlota Arriagada',
            'Francisca Menichetti',
            'Paola Gallardo',
            'Marcela Ortega',
            'Macarena Ruz',
            'Carlos Garay',
            'Paloma Moreno',
            'Liliana Aymani',
            'Claudio Fiuca',
            'Isabel Solarza',
            'Cristian Lopesich',
            'Victoria Giacoman',
            'Mariana Donoso',
            'Ma de los Angeles Selman',
            'Laura Wallenstein',
            'Veronica Celedon',
            'Cecilia Bravo',
            'Maria Jose Bravo',
            'Cecilia Camus',
            'Catalina Bravo',
            'Anita Yunke',
            'Ricardo Melnick',
            'Francisca Varela',
            'Alfonso Bullomore',
            'Sara Orellana',
            'Francisco Leiva',
            'Alejandra Melo',
            'Yasna Cornejo',
            'Jose Palomo',
            'Gean Brunetto',
            'Roberto Busel',
            'Pilar Cosmelli',
            'Gracia Cosmelli',
            'Luz Cosmelli',
            'Dany Tadres',
            'Ingrid Bergen',
            'Javier Juanicotena',
            'Jorge Claidsac',
            'Paola Rios',
            'Carla Quevedo',
            'Andrea Bajardi',
            'Mariluz Ahumada',
            'Claudia Pino',
            'Constanza Vargas',
            'Adriana Muat',
            'Gonzalo Becerra',
            'Loreto Solari',
            'Yenny Farias',
            'Macarena Monsalve',
            'Erick Gomez',
            'Margarita Romeo',
            'Josselyn Centeno',
            'Guido Hernandez',
            'Jorge Quevedo',
            'Raquel Kubik',
            'Mariane Jimenez',
            'Gonzalo Aglicati',
            'Marcelo Agurto',
            'Jenny Lopez',
            'Margarita Asada',
            'John Parra',
            'Moises Gutierrez',
            'Pedro Bernal',
            'Matias Alarcon',
            'Veronica Navarrete',
            'Eugenio Perez',
            'Alejandra Tapia'
          );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // No se implementa la reversión de esta migración
    await queryRunner.query(`
            UPDATE client
            SET ruta = NULL
            WHERE nombre = '';
    `);
  }
}
